export const items = [
  {
    id: "7392",
    image: ["https://i.postimg.cc/XNDZ0grk/nfc10.jpg"],
    name: "Golem Kappa",
    price: 55000,
    endTime: "1 day 5 hours",
    owner: "nova",
    currentBid: 1200,
    buyOutPrice: 400000,
  },
  {
    id: "1458",
    image: [
      "https://i.postimg.cc/WbhkDHBy/nfc1.jpg",
      "https://i.postimg.cc/fbhtrTV4/nfc2.jpg",
      "https://i.postimg.cc/rmfDs1Qc/nfc9.jpg",
      "https://i.postimg.cc/4Nqhp1Zx/nfc4.jpg"
    ],
    name: "Robo Alpha",
    price: 10000,
    endTime: "1 day 8 hours",
    owner: "nova",
    currentBid: 800,
    buyOutPrice: 380000,
  },
  {
    id: "9234",
    image: ["https://i.postimg.cc/fbhtrTV4/nfc2.jpg"],
    name: "Mecha Beta",
    price: 15000,
    endTime: "1 day 3 hours",
    owner: "leo",
    currentBid: 950,
    buyOutPrice: 420000,
  },
  {
    id: "5671",
    image: ["https://i.postimg.cc/rmfDs1Qc/nfc9.jpg"],
    name: "Machine Iota",
    price: 50000,
    endTime: "1 day 6 hours",
    owner: "leo",
    currentBid: 1500,
    buyOutPrice: 450000,
  },
  {
    id: "3489",
    image: ["https://i.postimg.cc/4Nqhp1Zx/nfc4.jpg"],
    name: "Droid Delta",
    price: 25000,
    endTime: "1 day 4 hours",
    owner: "leo",
    currentBid: 1100,
    buyOutPrice: 390000,
  },
];
